name: "Test - Integration"

on:
  pull_request_target:
    paths:
    - '.github/workflows/test-integration-template.yaml'
    - '.github/workflows/test-integration.yaml'
    - '.github/actions/gke-login/**'
    - '.github/actions/workflow-vars/**'
    - '.tool-versions'
    - 'charts/**'
    types: [opened, closed, reopened, synchronize]

permissions:
  contents: read

jobs:
  test:
    name: Main
    permissions:
      contents: read
      id-token: write
      deployments: write
    secrets: inherit
    uses: ./.github/workflows/test-integration-template.yaml
    with:
      identifier: "${{ github.event.pull_request.number }}"
      persistent: "${{ contains(github.event.*.labels.*.name, 'test-persistent') }}"
      platforms: "gke,rosa"
      flows: "install,upgrade"
      git-ref: ${{ github.event.pull_request.head.sha }}
