#
# Camunda - v8.2
# https://docs.camunda.io/docs/next/reference/announcements/#camunda-82
#

global:
  # https://github.com/camunda/camunda-platform/releases
  # https://hub.docker.com/u/camunda
  image:
    # renovate: datasource=github-releases depName=camunda/camunda-platform
    tag: 8.2.20

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 0.23.2

identity:
  keycloak:
    # https://hub.docker.com/r/bitnami/keycloak/tags
    image:
      repository: bitnami/keycloak
      tag: 19.0.3
    postgresql:
      # https://hub.docker.com/r/bitnami/postgresql/tags
      image:
        repository: bitnami/postgresql
        tag: 15.4.0

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 3.10.6

webModeler:
  # Camunda Enterprise repository.
  # registry.camunda.cloud/web-modeler-ee
  image:
    # renovate: datasource=docker depName=camunda/web-modeler lookupName=registry.camunda.cloud/web-modeler-ee/modeler-restapi
    tag: 8.2.10

#
# Elasticsearch
#

elasticsearch:
  # https://hub.docker.com/r/elastic/elasticsearch/tags
  image: docker.elastic.co/elasticsearch/elasticsearch
  # renovate: datasource=docker depName=elasticsearch/elasticsearch lookupName=docker.elastic.co/elasticsearch/elasticsearch
  imageTag: 7.17.17

retentionPolicy:
  # https://hub.docker.com/r/bitnami/elasticsearch-curator/tags
  image:
    repository: bitnami/elasticsearch-curator-archived
    tag: 5.8.4
